apiVersion: v1
kind: Endpoints
metadata:
  name: mytest-cluster
subsets:
  - addresses:
      - ip: 10.1.0.7
    ports:
      - name: myport
        port: 30870
        protocol: TCP
  - addresses:
      - ip: 10.1.0.6
    ports:
      - name: myport
        port: 30870
        protocol: TCP
  - addresses:
      - ip: 10.1.0.5
    ports:
      - name: myport
        port: 30870
        protocol: TCP