apiVersion: v1
kind: Service  
metadata:
   name: nginx-loadbalancer
   labels:
      app: nginx
    annotations:
      cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:    #selects the pods with label matches app=nginx
     app: nginx  
  #	setting the type as NodePort
  type: LoadBalancer
  ports:
    - port: &target 80
      name: http
      targetPort: *target
    - port: 443
      name: https
      targetPort: *target